### ISSUE TITLE
Cambiar un error en los datos 

### ISSUE THREAD

**Issue by ldarriba** [manuparra/mparra-csic-github#2]
@manuparra este dato no es correcto: 2021-10-05 15:45,5287.0,4123.0,3952.0
hay que substituirlo por 2021-10-05 18:55,5287.0,4123.0,3952.0

**Comment by manuparra** [comment]
@mapereztorres Hola podrías revisar estos datos

**Comment by mapereztorres** [comment]
@manuparra, ya he revisado los datos!
